# Fichiers sources
SRCS = main.cxx Point.cxx

# Nom de l'exécutable
TARGET = PointExecutable:

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)
# Nettoyage des fichiers temporaires
clean:
	rm -rf $(TARGET)
# Exécutable
run:
	./$(TARGET)