# Fichiers sources
SRCS = main.cxx Somme.cxx

# Nom de l'exécutable
TARGET = SommeExe:

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)
# Nettoyage des fichiers temporaires
clean:
	rm -f $(TARGET)
# Exécutable
run:
	./$(TARGET)
