# Fichiers sources
SRCS = main.cxx Somme.cxx

# Nom de l'exécutable
TARGET = Exe.exe

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)
# Nettoyage des fichiers temporaires
clean:
	del /f /q $(TARGET)
# Exécutable
run:
	./$(TARGET)
