# Fichiers sources
SRCS = main.cxx Message.cxx

# Nom de l'exécutable
TARGET = Message:

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)
# Nettoyage des fichiers temporaires
clean:
	rm -rf $(TARGET)
# Exécutable
run:
	./$(TARGET)
