# Fichiers sources
SRCS = main.cxx Message.cxx

# Nom de l'exécutable
TARGET = Message.exe

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)

# Nettoyage des fichiers temporaires
clean:
	del /f /q $(TARGET)

# Exécutable
run:
	$(TARGET)
