# Fichiers sources
SRCS = main.cxx Message.cxx

# Nom de l'exécutable
TARGET = bg:

# Commande de compilation
all:
	g++ $(SRCS) -o $(TARGET)
# Nettoyage des fichiers temporaires
clean:
	rm -f $(TARGET)
# Exécutable
run:
	$(TARGET)
